libraries:
  aravis:
    name: aravis
    pkg_sha: "03f5d736c4e1014c2668b37468a3c1c3af8edd08badc1c766f661ddd69a3658a"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31.dev1"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "95186639afc566c4235ad95ba86bb1fb29d4af26983122d689eb2bb86ed970cf"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31.dev1"

  ion_kit:
    name: ion-kit
    pkg_sha: "f99f81f9f415241c0327b983473583e8ae20ab187e9d6a5aebc1e74f38955ecf"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v3.2.7"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "905860d6b194c29275c08e1d7d9c6a84143284a368cc47366101678acb1489b8"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.4.1"

  gst_tool:
    name: "gstreamer tools"
    pkg_sha: "e4ec3c67dad8aab6b9cd684b2429e2726d43c248ee9fd5c18455dcd80c419e1d"
    git_repo: "https://github.com/Sensing-Dev/gst-plugins"
    version: "v1.22.5.8"

  gst_plugins:
    name: "gstreamer plugins"
    pkg_sha: "28e8a224b7f5b1de23e45bd680f56845bd792a911315a0bcfa2064af1c1aa1d0"
    git_repo: "https://github.com/Sensing-Dev/gst-plugins"
    version: "v1.22.5.8"
