libraries:
  aravis:
    name: aravis
    pkg_sha: "1f0ef68a9d33f9bb0c53361131bf73d67ffd3ebb4140758d914489884da93b97"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "0.8.30-internal"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "79a3a94c56d65fc63312cbb258f48be542993543fb74a33aaa8ab7ebc5c76354"
    git_repo: "" # use recipe here for appropriate version
    version: "0.8.30-internal"

  pygobject:
    name: pygobject
    pkg_sha: "eea9465b7cbf1420ee3b3d8a78f6cfa3feeff89ffade7ab1874ebb25d7078037"
    git_repo: "https://gitlab.gnome.org/GNOME/pygobject.git"
    version: "3.42.2"

  ion_kit:
    name: ion-kit
    pkg_sha: "75bf579f5465d67a4e21ffca2eaf0325216cc184c4b77d2f0b7f9cec139f9842"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v1.8.3"

  opencv:
    name: opencv
    pkg_sha: "cac31973cd1c59bfe9dc926acbde815553d23662ea355e0414b5e50d8f8aa5a8"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.5.5"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "bdcf560332bf90dc07ebd50d931f86003fc8cbd54336009e03828d8aa45f965d"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.2.8"


