libraries:
  aravis:
    name: aravis
    pkg_sha: "de971eaa037b60821bdb0ea19fff4be6f2f4fec4fcb464186f7631340e30c1c8"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31.post1"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "5c6aea5ecd4d13099652831f39363bac22301d8233dfa8e3084a4c4b5f9a3cbc"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31.post1"

  ion_kit:
    name: ion-kit
    pkg_sha: "6714b46f4f9f6db0806e78e69e1fee6188e520a5dfca5b134d1e007ae410fa33"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v3.2.6"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "e3bde8fce1b293d2db25bbfb0244e7c3245e523b7d64bf78ef26b5585e585959"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.3.5"

  gst_tool:
    name: "gstreamer tools"
    pkg_sha: "e4ec3c67dad8aab6b9cd684b2429e2726d43c248ee9fd5c18455dcd80c419e1d"
    git_repo: "https://github.com/Sensing-Dev/gst-plugins"
    version: "v1.22.5.8"

  gst_plugins:
    name: "gstreamer plugins(base/good)"
    pkg_sha: "28e8a224b7f5b1de23e45bd680f56845bd792a911315a0bcfa2064af1c1aa1d0"
    git_repo: "https://github.com/Sensing-Dev/gst-plugins"
    version: "v1.22.5.8"